image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - package

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/tarent/academy_api_doc:latest .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/tarent/academy_api_doc:latest